### PR TITLE
Cleanup regular expressions and refactor structure definition

### LINKED ISSUE #23: Regular expressions for primitives are not anchored
There are several regular expressions that end up in the metadata.rb file.  These expressions are not anchored, which causes them to be too liberal in what they match.

This is because regular expressions defined in xml schema are automatically anchored, making it necessary for this to be done explicitly in any language implementation that does not also do that automatically.

### PR DESCRIPTION
**Pull request by olbrich**
* comply with rubocop's suggestions about regular expressions
* refactor handling of base64binary type to make it easier to understand and slightly more restrictive (we now have a restriction that the number of non-whitespace characters must be a multiple of 4)
* refactor Structure Definition's data_type? method so it doesn't duplicate logic that exists in FHIR.primitive? 
* move FHIR::Model#primitive? to a class method in FHIR because the method itself does not care about the state of an instance and is a generally useful method.

fixes #23 as well.

### CODE REVIEW

**Comment by jawalonoski** [comment]
When you refactored `lib/fhir_models/fhir_ext/structure_definition.rb` to use the `FHIR.primitive?` method you lost support for `id`, `oid`, `date`, `datetime`, and `time`.

**Comment by olbrich** [comment]
@jawalonoski ok, I'll take a closer look at that one.

**Comment by jawalonoski** [comment]
@olbrich Sadly, yes. The 'validation_fixes` branch (not yet a pull request) may rectify this.

**Comment by olbrich** [comment]
@jawalonoski it looks like the original implementation of `is_primitive?` did not include the `oid`, `id`, `date` and `datetime`, and `time`.  It did include `xhtml`, which is not listed as a primitive type according to the current standard (http://build.fhir.org/datatypes.html#primitive).  It looks like the definition of primitive types has changed a bit across FHIR versions.  I'll update the `primitive?` method to include those unhandled types.

Does it make sense for `primitive?` to ever return true for a datatype of `xhtml` since it's not a primitive type?

**Comment by jawalonoski** [comment]
Probably -- since we've talked about supporting multiple versions... we're planning on adding back-support for DSTU2, where we'll need `xhtml` so if you could keep that it will be useful.

**Comment by jawalonoski** [comment]
The original implementation of `is_primitive?` did not -- correct -- but the similar method `data_type?` in the `fhir_ext/structure_definition.rb` did support those primitive types.

**Comment by olbrich** [comment]
@jawalonoski I don't see `xhmtl` as a primitive data type in DSTU2 either.

**Comment by jawalonoski** [comment]
@olbrich It exists. See http://hl7.org/fhir/DSTU2/narrative.html#xhtml and https://github.com/fhir-crucible/fhir_dstu2_models/blob/master/lib/models/profiles/profiles-types.xml#L5855

**Comment by olbrich** [comment]
Interesting.... weird that it's not called out explicitly as a primitive type.

**Comment by jawalonoski** [comment]
Bump. Just FYI, I've been waiting for you to add those other data types before I merge this PR.

**Comment by olbrich** [comment]
@jawalonoski yeah, just haven't had the bandwidth to add them yet.

**Comment by olbrich** [comment]
This PR also addresses #23

**Pull request merged**
